# Generated by Django 5.2.12 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
