# Generated by Django 5.2.12 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_diaryentry_start_time_diaryentry_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
